config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root  'books#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def top
	end

  def index
  	@books = Book.all
    @book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end



  def create
  	@book = Book.new(book_params)
  	if @book.save
      flash[:notice] = 'Book was successfully created.'
    redirect_to book_path(@book) 
  else
    @books = Book.all
    flash[:notice] = 'created error'
    render "index"
  end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
  	redirect_to book_path(@book)
  else
    flash[:notice] = 'updated error'
    render "edit"
  end
end

   def destroy
   	book = Book.find(params[:id])
   	book.destroy
    flash[:notice] = 'Book was successfully destroyed.'
   	redirect_to books_path
   end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% if flash[:notice] %>
<p><%= flash[:notice] %></p>
<% end %>

<h1>Edit Book</h1>
<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <div class="submit">
    <%= f.submit 'Update Book' %>
    </div>
<% end %>
<%= link_to "show", book_path %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if flash[:notice] %>
<p><%= flash[:notice] %></p>
<% end %>
<h1>Books</h1>
<table>
	<thead>
		<tr>
			<th>Title</th>
			<th> Body</th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
		<td><%= book.title %></td>
		<td><%= book.body %></td>
		<td><%= link_to 'Show', book %></td>
		<td><%= link_to 'Edit', edit_book_path(book) %></td>
		<td><%= link_to 'Destroy', book_path(book), method: :delete, data: {confirm: 'Are you sure?' } %></td>

	</tr>
	<% end %>
</tbody>
</table>
	<h2>New book</h2>
<%= render 'layouts/error_messages', model: @book %>
<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<div class="submit">
<%= f.submit 'Create Book' %>
</div>


<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
<p><%= flash[:notice] %></p>
<% end %>
	<p>Title: <%= @book.title %>
</p>
<p>Body: <%= @book.body %>
</p>
<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Back", books_path %>
<%= link_to "Destroy", book_path(@book), method: :delete %>

app/views/books/top.html.erb
	<h1>ようこそ <strong>Bookers</strong> へ！</h1>
	<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や、</p>
	<p>印象を共有し交換することができます</p>
	<u><p>
		<a href="/books">start</a>
	</p></u>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class = "alert alert-warning">
	<ul>
		<% model.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>